# Generated by Django 4.2.4 on 2023-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
