# Generated by Django 4.2.4 on 2023-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_queue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='window_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
