# Generated by Django 4.2.4 on 2023-08-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_operator_window_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='operator',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='window_number',
        ),
        migrations.AlterField(
            model_name='queue',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='operator',
            name='branch',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='apps.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='branch',
            field=models.ForeignKey(default=232, on_delete=django.db.models.deletion.CASCADE, to='apps.branch'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('branch', 'number')},
        ),
    ]
